### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by david-dickinson** [yorkis-diaz/OpenPlay#2]
## MVP List
- [x] split the reservations and browse location MVPs into separate items
- [x] don’t worry about the restaurant/establishment creation process: this app won't need to be functional from the company side
- [x] redo the MVP order (search/view events/tournaments, reservations, ratings/reviews, favorites)
- [x] make saved events the last MVP and absorb the profile MVP into the reservations MVP for now

## Schema
- [x] events table should have the same properties that restaurants have on the original
    - [x] include `lat`, `lng` floats for your location information
    - [x] replace `start_time` and `date` with the ability to make reservations at different times like one would withe restaurants
- [x] reviews should connect to `reservation_id`s so attendance is confirmed and multiple reviews per user are possible
- [x] no need for a `reviews.title`

## Sample State
- [x] update to reflect changes in schema
- [x] change snake_case to camelCase
- [x] saved events will only be necessary for the current user, not other users
- [x] add a session slice of state

## Backend Routes
- [x] reservations shouldn’t require GET request with an `:event_id` wildcard - they're only needed on user’s show page
- [x] `GET /api/events/:event_id/reservations` should be used for getting single event’s reservation, not single user’s
- [x] `GET /api/events/:event_id/reviews` should be used for getting single event’s reviews, not user
- [x] POST review to `reservation_id` route (rather than `event_id` for the reasons discussed above)
- [x] add BERs for saved events

## Frontend Routes
- [x] list only the components available at each FER: eg, `/` should have a `<GreetingComponent>` and `<SearchBarForm>`, but not other FERs like `/login` or `/users/:id`
- [x] add FER to search and contain an events index
- [x] `/users/:id` page should have many `<ReservationItems>` and `<ReviewItems>` in indexes
- [x] `/events/:id` page should have only one `<ReservationForm>` and an index of many `<ReviewItems>`
    - [x] expand on `<EventDetails>` to include photos, display information (name, info, etc), map component

**Comment by yorkis-diaz** [comment]
Issues addressed
